name: Compilar SDK VB.NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019  # Usamos Windows con Visual Studio preinstalado

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Copiar la librería SigPlusNET.dll
        run: copy SigPlusNET.dll C:\Windows\Microsoft.NET\Framework\v4.0.30319\

      - name: Compilar el SDK en Visual Basic
        run: |
          mkdir output
          "C:\Windows\Microsoft.NET\Framework\v4.0.30319\vbc.exe" /target:winexe /reference:SigPlusNET.dll /out:output/SDK_Firma_Topaz.exe CapturaFirmaTopaz.vb

      - name: Subir el ejecutable compilado
        uses: actions/upload-artifact@v4
        with:
          name: SDK_Firma_Topaz
          path: output/SDK_Firma_Topaz.exe
